### PR TITLE
New feature : Oembed

### PR DESCRIPTION
**Pull request by kerjoa**
See https://oembed.com/
With new setting OEMBED :
add in video pages a link tag with type application/json+oembed and href to json representation of the URL video. https://oembed.com/#section4
add url oembed and buid the json representation of the URL video
oembed works also with private videos

### CODE REVIEW

**Comment by DrClockwork** [comment]
The oembed link did not appear in the head of video page when I did the tests.
I saw that the new block 'link_alternate' was not present in the base.html. I added the block to this file and now it's worked fine. 

Thank you for bringing this new feature!

**Comment by kerjoa** [comment]
Ho yes.. I had this line in the base.html of my theme and I forgot to put it also in the original file.
Thank you !

**Comment by DrClockwork** [comment]
Why did you close this PR ? It's fine for me with the bugfix I made directly on your branch, I was going to pass it in dev.

**Comment by kerjoa** [comment]
Sorry, bad action... It's my first pull request :-)

**Pull request merged**
